# Generated by Django 5.2 on 2025-04-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='module',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lms.course', verbose_name='Curso'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
