# Generated by Django 5.2 on 2025-05-03 20:03

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_userlecturesrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_content',
            field=models.FileField(upload_to='lectures/videos/', validators=[lms.models.validate_mp4_extension], verbose_name='Conteúdo em vídeo'),
        ),
    ]
