# Generated by Django 5.2 on 2025-05-17 20:56

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_lecture_video_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='document_content',
            field=models.FileField(blank=True, null=True, upload_to='lectures/documents/', validators=[lms.models.validate_pdf_extension], verbose_name='Conteúdo em vídeo'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_content',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/', validators=[lms.models.validate_mp4_extension], verbose_name='Conteúdo em vídeo'),
        ),
    ]
