# Generated by Django 5.2 on 2025-06-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lecture'),
        ),
    ]
